name: Publish and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Hltv.sln

      - name: Build solution
        run: dotnet build Hltv.sln --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish OverlayWindow.csproj `
              --configuration Release `
              --output ./publish `
              --runtime win-x64 `
              --self-contained true

      - name: Organize release folder
        run: |
          mkdir release
          mkdir release/server
          copy publish\LiveStrike.exe release\
          copy publish\LiveStrike.pdb release\

          copy publish\server.js release\server\
          copy publish\test.js release\server\
          copy publish\site-configs.js release\server\
          copy publish\package.json release\server\
          copy publish\package-lock.json release\server\

      - name: Create ZIP archive
        run: powershell Compress-Archive -Path release\* -DestinationPath release.zip

      - name: Upload release.zip
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: release.zip

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download built zip
        uses: actions/download-artifact@v4
        with:
          name: release-zip
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
